imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: en }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale: %locale%
    session: ~
    trust_proxy_headers: false

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles: []
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool: { type: memory }

# Parameters
parameters:
  pdo.db_options:
    db_table:		session
    db_id_col:		session_id
    db_data_col:	session_value
    db_time_col:	session_time
  search.class:   My\UiBundle\Service\Search
  scraper.class:  My\UiBundle\Service\Scraper

# Services
services:
  pdo:
    class: PDO
    arguments:
      - "mysql:dbname=%database_name%"
      - %database_user%
      - %database_password%

  session.storage.pdo:
    class:		Symfony\Component\HttpFoundation\SessionStorage\PdoSessionStorage
    arguments:	[@pdo, %session.storage.options%, %pdo.db_options%]

  search:
    class:       %search.class%
  scraper:
    class:       %scraper.class%
  listener.search:
    class:       My\UiBundle\Listener\SearchListener
    tags:
      - { name: doctrine.event_listener, event: postPersist }
      - { name: doctrine.event_listener, event: postRemove }
      - { name: doctrine.event_listener, event: postUpdate }
