<?php

namespace My\UiBundle\Repository;

use Doctrine\ORM\EntityRepository;
use My\UiBundle\Entity\Category;

/**
 * CategoryRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    /**
     * Find last viewed
     * @return Category[]
     */
    public function findLastViewed()
    {
        $query = $this->getEntityManager()->createQuery("
                SELECT c
                FROM MyUiBundle:Category c
                WHERE c.lastViewedAt IS NOT NULL
                ORDER BY c.lastViewedAt DESC
            ")
            ->setMaxResults(6);
        return $query->getResult();
    }
}
