<?php

namespace My\UiBundle\Repository;

use Doctrine\ORM\EntityRepository;
use My\UiBundle\Entity\Category;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
	/** Create Defaults */
	public function createDefaults()
	{
		$em = $this->getEntityManager();

		// movies
		$category = $this->findOneByCode('201');
		if (!$category) {
			$category = new Category();
			$category->setCode('201');
			$category->setMedia('Video');
			$category->setName('Movies');
			$category->setScrape(false);
			$category->setPages(0);
			$em->persist($category);
		}

		// highres movies
		$category = $this->findOneByCode('207');
		if (!$category) {
			$category = new Category();
			$category->setCode('207');
			$category->setMedia('Video');
			$category->setName('Highres - Movies');
			$category->setScrape(true);
			$category->setPages(1);
			$em->persist($category);
		}

		// tv shows
		$category = $this->findOneByCode('205');
		if (!$category) {
			$category = new Category();
			$category->setCode('205');
			$category->setMedia('Video');
			$category->setName('TV Shows');
			$category->setScrape(false);
			$category->setPages(0);
			$em->persist($category);
		}

		// highres - tv shows
		$category = $this->findOneByCode('208');
		if (!$category) {
			$category = new Category();
			$category->setCode('208');
			$category->setMedia('Video');
			$category->setName('Highres - TV Shows');
			$category->setScrape(true);
			$category->setPages(2);
			$em->persist($category);
		}

		// games - pc
		$category = $this->findOneByCode('401');
		if (!$category) {
			$category = new Category();
			$category->setCode('401');
			$category->setMedia('Games');
			$category->setName('Games - PC');
			$category->setScrape(true);
			$category->setPages(1);
			$em->persist($category);
		}
	}
}