<?php

namespace My\UiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UploaderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UploaderRepository extends EntityRepository
{
}
